### ISSUE TITLE
変換範囲を指定していない状態で変換を実行するとエラーが発生する

### ISSUE THREAD

**Issue by changami** [penginryo/AsciiConverterPlugin#10]
範囲を選択していない状態で各toASCII変換を実行した際、コンソールにエラーが表示されているので解決してください。  
## DecimalToAsciiCommand

27行目, datas = int(decimal):

```
ValueError: invalid literal for int() with base 10: ''
```
## HexaDecimalToAsciiCommand

73行目, datas = eval(hexa):

```
SyntaxError: unexpected EOF while parsing
```
## BinaryToAsciiCommand

88行目, datas = eval(binary):

```
SyntaxError: unexpected EOF while parsing
```

**Comment by bg-k** [comment]
完了しました、が、コンフリクト....

**Comment by changami** [comment]
4b167d7eb251792af7e4057ad0cb8930515bb495 からブランチ切りなおして対応してもらえるとmergeが超楽になるなー
何か理由あって途中からブランチ切った？？
