### ISSUE TITLE
Thinking about key map

### ISSUE THREAD

**Issue by changami** [penginryo/AsciiConverterPlugin#8]
現状(230f6a59eeff9c00b872c5e348c91558a9b56d53)、逆の変換を行いたい場合のキーマップはこのようになっている。

```
ctrl+a, ctrl+d => ASCII to Decimal
ctrl+z, ctrl+d => Decimal to ASCII
```

```
ctrl+a, ctrl+h => ASCII to HexaDecimal
ctrl+z, ctrl+h => HexaDecimal to ASCII
```

入力順序を逆にするだけで逆の変換が行われるようなキーマップに設定したほうが使いやすいのではないか。

**Comment by bg-k** [comment]
僕のST2にインストールされているキーマップのせいなのかわかりませんが、
ctrl+h, ctrl+a
は動作の確認が取れませんでした。
再度検証してみます。

**Comment by changami** [comment]
変換前後のイニシャルにこだわらなくても何か使いやすいキーマップはないか、という方向でも考えてみます。

**Comment by changami** [comment]
これは後からいくらでも修正が利くので、キーマップを気にせずBinaryの実装は進めてしまってください！

**Comment by bg-k** [comment]
:ok_hand:

**Comment by changami** [comment]
これはいかがでしょう

```
ctrl+c, ctrl+d => Convert ASCII to Decimal
ctrl+r, ctrl+d => Reconvert Decimal back to ASCII
```

**Comment by bg-k** [comment]
sounds good!
